### ISSUE TITLE
2.0.6 have error  window of undefined on SSR - blank page on IE11

### ISSUE THREAD

**Issue by dimasch** [filrak/vue-offline#10]
Hi, Filip @filrak, we have workaround and create pull.

https://stackoverflow.com/questions/53516050/vue-cli-3-0-project-not-working-on-ie11-script1003-expected-error-with-bla

**Comment by filrak** [comment]
Thanks! So I'm waiting for PR :)

**Comment by filrak** [comment]
@dimasch will you propose the PR or should I take care of this?

**Comment by dimasch** [comment]
I am wait additional info from my colleague, requested info from him again (he was in the testing phase for this point)
