### ISSUE TITLE
Removing events

### ISSUE THREAD

**Issue by josteph** [filrak/vue-offline#2]
Hi there, thanks for the plugin. But it's better to remove events by using beforeDestroy hook. Here is more or less what it should be:
```
mounted() {
    window.addEventListener('online', this.updateStatus)
    window.addEventListener('offline', this.updateStatus)
},
beforeDestroy() {
    window.removeEventListener('online', this.updateStatus)
    window.removeEventListener('offline', this.updateStatus)
},
methods: {
    updateStatus() {
        // do network change code here.
    }
}
```

**Comment by filrak** [comment]
Hi, thank you, I'll add this ;) (or you can propose PR with this if you want to contribute)

**Comment by filrak** [comment]
Ok, I'll do it this weekend (unfortunetly had no time in the previous one), thanks ;)
