### ISSUE TITLE
global mixin and performance

### ISSUE THREAD

**Issue by chriscdn** [filrak/vue-offline#5]
There is performance problem when registering the mixin as a global.  The `mounted()` hook gets called on each component, which means potentially 100s of calls to `window.addEventListener`.

	window.addEventListener('online',  onlineHandler)
	window.addEventListener('offline',  offlineHandler)
	
Chrome seems to handle this fine.  IE, not so well.

**Comment by filrak** [comment]
@chriscdn this is why you have `VueOfflineMixin` which you can inject instead of plugin

**Comment by filrak** [comment]
There will be an huge update next week tho which should eliminate this problem
