### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by parsedout** [filrak/vue-offline#6]
Hello.  I'm having an error show up on "npm run build" command.  Seems to be related to this newest module.

ERROR in static/js/vendor.5ed2498b4e9577849f57.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue-offline/lib/vue-offline.js:118,0][static/js/vendor.5ed2498b4e9577849f57.js:42128,6]

**Comment by filrak** [comment]
Can you post any link for reproduction or tell me a little bit more about your env? With vue-cli 3.0 everything seems fine with dev and prod builds

**Comment by filrak** [comment]
Can you please update to 2.0.2 and tell if problem is still occuring?

**Comment by parsedout** [comment]
Updated to 2.0.2 and the build process goes without error.  Thank you for the quick fix!
