### ISSUE TITLE
VueOfflineStorageKey duplicating

### ISSUE THREAD

**Issue by ViacheslavZyrianov** [filrak/vue-offline#7]
If I try to save locaStorage item with same name but another content, the `VueOfflineStorageKeys` array is being replenished with duplicated items, like `['userData', 'userData', 'userData', 'userData']` and so on.

**Comment by filrak** [comment]
fixed with https://github.com/filrak/vue-offline/commit/e974cc3bb71798cb661956d0c86131ed5c678ba6
