### ISSUE TITLE
I'm getting undefined for this.$offlineStorage.get('data')

### ISSUE THREAD

**Issue by Reollyn** [filrak/vue-offline#9]
Hello,

I'm getting `undefined` when I try ti get the data from `this.$offlineStorage.get('obdDevice')`. I'm trying to get it on `mounted: ()` and on `beforeDestroy: ()`. Is that a bug or I'm doing something wrong?

Here is the log for `this.$offlineStorage`, but `get()` doesn't work.

<img width="418" alt="screenshot 2018-11-28 at 12 38 09" src="https://user-images.githubusercontent.com/20517519/49149614-d7c47880-f30a-11e8-8b6b-1e27a7ba967f.png">

**Comment by filrak** [comment]
Hey, which version are you using?
There was a small bug fixed here:
https://github.com/filrak/vue-offline/commit/e974cc3bb71798cb661956d0c86131ed5c678ba6

updating the lib should do the job
